# use "ansible-playbook main.yml --ask-become-pass"
- name: install packages and configure settings
  hosts: localhost
            
  tasks:
    - name: update
      apt:
        update_cache: yes
      become: true
        
    - name: refresh snap 
      command: snap refresh
      become: true 
      
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/configure.yml
    - include_tasks: tasks/lua-lsp.yml
      

