- name: Install packages and configure settings
  hosts: localhost
  become: yes
  pre_tasks:
    - name: update cache
      apt: 
        update_cahce: yes
        
  vars:
    build_directory: "{{ ansible_env.HOME }}"
      
  tasks:
    - include: tasks/packages.yml
    - include: tasks/configure.yml
    - inlcude: tasks/lua-lsp.yml
      
