- name: create bin dir 
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    
- name: download latest lua-lsp
  get_url:
    url: "{{ lookup('url', 'https://api.github.com/repos/LuaLS/lua-language-server/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://(.*?).tar.gz)', '\\1') | first }}"
    dest: '{{ ansible_env.HOME }}/Downloads/lua-lsp.tar.gz'
            
- name: create lua-lsp dir 
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/lua-lsp"
    state: directory

- name: extract lua-lsp package
  unarchive:
    src: '{{ ansible_env.HOME }}/Downloads/lua-lsp.tar.gz'
    dest: '{{ ansible_env.HOME }}/.local/bin/lua-lsp'
    remote_src: yes
    
#- name: remove tar.gz file
#  file:
#    path: '{{ ansible_env.HOME }}/Downloads/lua-lsp.tar.gz'
#    state: absent

